project_id = "yioldpwkkgsdsukxfcnr"

[functions.backfill-producer-net-brl]
verify_jwt = false


[functions.hotmart-backfill]
verify_jwt = false

[functions.hotmart-orders-backfill-14d]
verify_jwt = false


[functions.hotmart-webhook]
verify_jwt = false

[functions.hotmart-ledger-full-backfill]
verify_jwt = false


[functions.hotmart-ledger-brl-backfill]
verify_jwt = false


[functions.hotmart-products]
verify_jwt = false


[functions.meta-insights-cron]
verify_jwt = false

[functions.orders-full-backfill]
verify_jwt = false



[functions.whatsapp-webhook]
verify_jwt = false

[functions.backfill-item-type]
verify_jwt = true


[functions.recover-item-type]
verify_jwt = false

[functions.fix-legacy-ledger-brl]
verify_jwt = false


[functions.csv-ledger-v21-import]
verify_jwt = false
<<<<<<< Updated upstream
max_duration = 300

[functions.export-om-full]
verify_jwt = false

[functions.export-csv-utf8]
verify_jwt = false

[functions.export-operational-data]
=======

[functions.meta-oauth-state]
verify_jwt = false

[functions.meta-oauth-callback]
>>>>>>> Stashed changes
verify_jwt = false
