project_id = "jcbzwxgayxrnxlgmmlni"

[functions.hotmart-api]
verify_jwt = true

[functions.send-invite-email]
verify_jwt = true

[functions.meta-oauth-callback]
verify_jwt = false

[functions.meta-api]
verify_jwt = true
max_duration = 300
