project_id = "mqaygpnfjuyslnxpvipa"

# =====================================
# HOTMART / FINANCE
# =====================================

[functions.backfill-producer-net-brl]
verify_jwt = false

[functions.hotmart-backfill]
verify_jwt = false

[functions.hotmart-orders-backfill-14d]
verify_jwt = false

[functions.hotmart-webhook]
verify_jwt = false

[functions.hotmart-ledger-full-backfill]
verify_jwt = false

[functions.hotmart-ledger-brl-backfill]
verify_jwt = false

[functions.hotmart-products]
verify_jwt = false

[functions.orders-full-backfill]
verify_jwt = false

[functions.fix-legacy-ledger-brl]
verify_jwt = false

[functions.csv-ledger-v21-import]
verify_jwt = false

# =====================================
# META
# =====================================

[functions.meta-oauth-state]
verify_jwt = false

[functions.meta-oauth-callback]
verify_jwt = false

[functions.meta-insights-cron]
verify_jwt = false

# =====================================
# SOCIAL LISTENING
# =====================================

[functions.social-comments-api]
verify_jwt = false

# =====================================
# META API
# =====================================

[functions.meta-api]
verify_jwt = false

# =====================================
# WHATSAPP
# =====================================

[functions.whatsapp-webhook]
verify_jwt = false

# =====================================
# UTILS / RECOVERY
# =====================================

[functions.backfill-item-type]
verify_jwt = true

[functions.recover-item-type]
verify_jwt = false

# =====================================
# EXPORTS
# =====================================

[functions.export-om-full]
verify_jwt = false

[functions.export-csv-utf8]
verify_jwt = false

[functions.export-operational-data]
verify_jwt = false


[functions.meta-save-accounts]
enabled = true
verify_jwt = false
import_map = "./functions/meta-save-accounts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/meta-save-accounts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/meta-save-accounts/*.html" ]
